name: Semgrep CI (T1.10)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep with baseline
        run: |
          semgrep ci \
            --config=semgrep.yml \
            --baseline-commit origin/main \
            --error \
            --sarif --sarif-output semgrep.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
